name: connectivity_plus_test
description: Connectivity+ test
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  connectivity_plus: ^2.2.1
  flutter:
    sdk: flutter
  provider: ^6.0.2

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.1.0

flutter:
  uses-material-design: true
