name: Connectivity+

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  widget_test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
    - run: flutter config --enable-linux-desktop
    - run: flutter test

  integration_test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
    - run: flutter config --enable-linux-desktop
    - run: |
        sudo apt update
        sudo apt install -y clang cmake curl ninja-build libgtk-3-dev pkg-config unzip
        sudo apt install -y xvfb
    - run: flutter doctor -v
    - run: xvfb-run -a flutter test integration_test
